

sudo: required

env:
# section utile pour vos variables d'environnement.
# /!\ N'Y METTEZ PAS d'informations sensibles !
# pour cela, utilisez les fonctionnalités de Travis CI

before_install:
  - gem install prawn -v 2.1.0   # dependance d'asciidoctor
  - gem install asciidoctor      # pour générer votre HTML
  - gem install asciidoctor-pdf --pre # pour générer le PDF

script:
# mettez ici compilation et génération de documentation

deploy:
  # section de configuration des github pages
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: gh-pages
  on:
    branch: master


